/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 * 
 * PAQUETES
 */
package disquera.gui;

/**
 * 
 * IMPORTACIONES
 */
import javax.swing.JOptionPane;
import disquera.beans.Disco;
import disquera.datos.DiscoDAO;
import disquera.exceptions.DiscoException;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ITALO SABATTINI AND ROBERTO FUENTES
 */

/**
 * 
 * CLASES
 */
public class FrmIngresoDisco extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmIngresoDisco.class.getName());

    /**
     * Creates new form FrmIngresoCancion
     */
    ImagenFondo ejemplo = new ImagenFondo();   
    public FrmIngresoDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRanking = new javax.swing.ButtonGroup();
        jpPanelPrincipal = new ImagenFondo();
        txtDuracion = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        lblDuracion = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBloquear = new javax.swing.JButton();
        btnDesbloquear = new javax.swing.JButton();
        cbGenero = new javax.swing.JComboBox<>();
        cbAnio = new javax.swing.JComboBox<>();
        rbActual = new javax.swing.JRadioButton();
        rbnunca = new javax.swing.JRadioButton();
        rbEstuvo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Discos");

        txtDuracion.setBackground(new java.awt.Color(255, 255, 255));
        txtDuracion.setForeground(new java.awt.Color(0, 0, 0));

        txtArtista.setBackground(new java.awt.Color(255, 255, 255));
        txtArtista.setForeground(new java.awt.Color(0, 0, 0));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setToolTipText("");

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lblDuracion.setBackground(new java.awt.Color(255, 255, 255));
        lblDuracion.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setText("duracion:");
        lblDuracion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblArtista.setBackground(new java.awt.Color(255, 255, 255));
        lblArtista.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblArtista.setForeground(new java.awt.Color(255, 255, 255));
        lblArtista.setText("Artista:");
        lblArtista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblId.setBackground(new java.awt.Color(255, 255, 255));
        lblId.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID:");
        lblId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblGenero.setBackground(new java.awt.Color(255, 255, 255));
        lblGenero.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("genero:");
        lblGenero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRanking.setBackground(new java.awt.Color(255, 255, 255));
        lblRanking.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblRanking.setForeground(new java.awt.Color(255, 255, 255));
        lblRanking.setText("ranking:");
        lblRanking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAnio.setBackground(new java.awt.Color(255, 255, 255));
        lblAnio.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(255, 255, 255));
        lblAnio.setText("año:");
        lblAnio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Felix Titling", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("INGRESE LOS DATOS DEL DISCO");
        lblTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        lblNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBloquear.setBackground(new java.awt.Color(255, 255, 255));
        btnBloquear.setForeground(new java.awt.Color(0, 0, 0));
        btnBloquear.setText("Bloquear");
        btnBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearActionPerformed(evt);
            }
        });

        btnDesbloquear.setBackground(new java.awt.Color(255, 255, 255));
        btnDesbloquear.setForeground(new java.awt.Color(0, 0, 0));
        btnDesbloquear.setText("Desbloquear");
        btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearActionPerformed(evt);
            }
        });

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar -", "ROCK", "REGUETON", "BACHATA", "ROMANTICOS", "POP", "REAGGE", "LATINO", "K-POP", "CLASICOS", "ELECTRO", "TANGO", "" }));
        cbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGeneroActionPerformed(evt);
            }
        });

        cbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar -", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        cbAnio.setToolTipText("");
        cbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnioActionPerformed(evt);
            }
        });

        bgRanking.add(rbActual);
        rbActual.setText("ACTUAL");
        rbActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActualActionPerformed(evt);
            }
        });

        bgRanking.add(rbnunca);
        rbnunca.setText("NUNCA");
        rbnunca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnuncaActionPerformed(evt);
            }
        });

        bgRanking.add(rbEstuvo);
        rbEstuvo.setText("ESTUVO");
        rbEstuvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEstuvoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelPrincipalLayout = new javax.swing.GroupLayout(jpPanelPrincipal);
        jpPanelPrincipal.setLayout(jpPanelPrincipalLayout);
        jpPanelPrincipalLayout.setHorizontalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(3, 3, 3)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblDuracion)
                        .addGap(10, 10, 10)
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(rbActual)
                        .addGap(12, 12, 12)
                        .addComponent(rbEstuvo)
                        .addGap(24, 24, 24)
                        .addComponent(rbnunca))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(8, 8, 8)
                        .addComponent(btnLimpiar)
                        .addGap(8, 8, 8)
                        .addComponent(btnCancelar)
                        .addGap(4, 4, 4)
                        .addComponent(btnBloquear)
                        .addGap(3, 3, 3)
                        .addComponent(btnDesbloquear)))
                .addGap(63, 63, 63))
        );
        jpPanelPrincipalLayout.setVerticalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitulo)
                .addGap(53, 53, 53)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtista)
                    .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDuracion)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRanking)
                    .addComponent(rbActual)
                    .addComponent(rbEstuvo)
                    .addComponent(rbnunca))
                .addGap(14, 14, 14)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnio)
                    .addComponent(cbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGenero)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCancelar)
                    .addComponent(btnBloquear)
                    .addComponent(btnDesbloquear))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * BOTONES
 */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        try
        {
            if (txtId.getText().trim().isEmpty() || 
                txtNombre.getText().trim().isEmpty() || 
                txtArtista.getText().trim().isEmpty() ||
                txtDuracion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se agregó ningún dato. Por favor complete los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int duracion = Integer.parseInt(txtDuracion.getText().trim());           
            String id = txtId.getText().trim();
            String nombre = txtNombre.getText().trim();
            String artista = txtArtista.getText().trim();
            String anioSeleccionado = (String) cbAnio.getSelectedItem();
            String genero = (String)cbGenero.getSelectedItem();
            String ranking = new String();
            
            if(rbActual.isSelected())
            {
                ranking = "Actual";
            }
            else if(rbEstuvo.isSelected())
            {
                ranking = "Estuvo";
            }
            else
            {
                ranking = "Nunca";
            }
           if (anioSeleccionado.equals("- Seleccionar -")) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un año", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return; // Detenemos aquí si no eligió año
            }   
            int anio = Integer.parseInt(anioSeleccionado);
            Disco oDisco = new Disco(id, nombre, artista, anio, duracion, ranking, genero);
            DiscoDAO oDiscoDAO = new DiscoDAO();
            boolean existe = oDiscoDAO.ValidarExistencia(id);   
            if (!existe) {
                oDiscoDAO.IngresoDisco(oDisco);
                JOptionPane.showMessageDialog(this, "Operación realizada con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "El id ya se encuentra registrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(DiscoException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
        catch(NumberFormatException nex){
            JOptionPane.showMessageDialog(this, "Debe ingresar ", "Error de Registro", JOptionPane.WARNING_MESSAGE);               
                }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombre.setText("");
        txtId.setText("");
        txtDuracion.setText("");
        txtArtista.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        super.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearActionPerformed
        txtNombre.setEnabled(false);
        txtId.setEnabled(false);
        txtDuracion.setEnabled(false);
        txtArtista.setEnabled(false);
        rbActual.setEnabled(false);
        rbnunca.setEnabled(false);
        rbEstuvo.setEnabled(false);
        cbAnio.setEnabled(false);
        cbGenero.setEnabled(false);
    }//GEN-LAST:event_btnBloquearActionPerformed

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
        txtNombre.setEnabled(true);
        txtId.setEnabled(true);
        txtDuracion.setEnabled(true);
        txtArtista.setEnabled(true);
        rbActual.setEnabled(true);
        rbnunca.setEnabled(true);
        rbEstuvo.setEnabled(true);
        cbAnio.setEnabled(true);
        cbGenero.setEnabled(true);

    }//GEN-LAST:event_btnDesbloquearActionPerformed

    private void cbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGeneroActionPerformed

    private void cbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnioActionPerformed

    private void rbActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbActualActionPerformed

    private void rbnuncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnuncaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnuncaActionPerformed

    private void rbEstuvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEstuvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEstuvoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmIngresoDisco dialog = new FrmIngresoDisco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgRanking;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBloquear;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDesbloquear;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbAnio;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JPanel jpPanelPrincipal;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbActual;
    private javax.swing.JRadioButton rbEstuvo;
    private javax.swing.JRadioButton rbnunca;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    class ImagenFondo extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/img/ondasmoradas.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            super.paint(g);
            setOpaque(false);
        }
    }
}
